kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: security-app-full-access-role-binding
  namespace: security
subjects:
- kind: User
  name: dev@fabrikamgulf.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: security-app-full-access-role
  apiGroup: rbac.authorization.k8s.io
